#(a)
read.csv("C:/Users/HP/Downloads/Clt-data.csv")
data<-read.csv(file.choose())
#(b)
dim(data)
abc<-head(data,10)
#(c)
a<-mean(data$Wall.Thickness)
nrow(data)
hist(data$Wall.Thickness)
#(d)
abline(v=a,col='red')
aa<-sample(data[,1],10)
mean(aa)
hist(aa)
s=c()
hist(s)
for (i in 1:500)
{
  s[i]<-mean(sample(data[,1],1000,replace=TRUE))
}
hist(s)
par(mfcol=c(2,2))

